package com.voleksiienko.specforgeapi.core.domain.model.error;

public enum JsonMappingErrorCode implements ErrorCode {
    JSON_SAMPLE_PARSING_FAILED,
    JSON_SCHEMA_PARSING_FAILED,
    JSON_SCHEMA_VALIDATION_FAILED,
    JSON_SCHEMA_CIRCULAR_REF_FOUND,
    JSON_SCHEMA_UNRESOLVED_REF_FOUND,
    JSON_SCHEMA_CHILDREN_MAPPING_FAILED,
    JSON_SCHEMA_COMPOSITION_PROPERTY_DUPLICATE,
    JSON_SCHEMA_COMPOSITION_PROPERTY_MERGED,
    JSON_SCHEMA_PROPERTY_TYPE_INFERRED,
    JSON_SCHEMA_TYPE_DEFAULTED_TO_STRING,
    JSON_SCHEMA_TEMPORAL_FORMAT_DEFAULTED,
    JSON_SCHEMA_MAP_KEY_DEFAULTED_TO_STRING,
    JSON_SCHEMA_LIST_VALUE_DEFAULTED_TO_STRING;

    @Override
    public String getName() {
        return name();
    }
}
